// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyQ8edF24YisGtcKT68Gu7U6PvHoDtqk',
    appId: '1:537908387516:android:c383c526d498211de2bab9',
    messagingSenderId: '537908387516',
    projectId: 'bake-nation',
    databaseURL: 'https://bake-nation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bake-nation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJwU2fNTkttTr9S4bs9brb0vnRyO-78U',
    appId: '1:537908387516:ios:812afb014f6eb49be2bab9',
    messagingSenderId: '537908387516',
    projectId: 'bake-nation',
    databaseURL: 'https://bake-nation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bake-nation.firebasestorage.app',
    iosClientId: '537908387516-ie9f8r383ep0s7kl4ag29scq07691vng.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakenationStaff',
  );
}
